---
title: O Cold Standby lança o "Registro DataStoreException não existe"
description: Descrição
solution: Experience Manager
product: Experience Manager
applies-to: Experience Manager
keywords: KCS,AEM,coldstandby,DataStoreException
resolution: Resolution
internal-notes: https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668
bug: false
article-created-by: Vincent Frey
article-created-date: 5/12/2022 3:39:59 PM
article-published-by: Vincent Frey
article-published-date: 5/12/2022 3:40:16 PM
version-number: 2
article-number: KA-15610
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=8e6000c7-09d2-ec11-a7b5-0022480a8683
exl-id: d37d0338-be4f-4660-a4b2-cd1179717e07
source-git-commit: e8f4ca2dd578944d4fe399074fab461de88ad247
workflow-type: tm+mt
source-wordcount: '311'
ht-degree: 0%

---

# O Cold Standby lança o &quot;Registro DataStoreException não existe&quot;

## Descrição


<b>Problema:</b>
O modo de espera frio com arquivo dedicado Datastore lança um aviso sobre a falta de um blobid como aquele em 1.

<b>Detalhes:</b>
Isto é apenas um aviso, não um erro. Isso vem do fato de que o armazenamento de dados não tem como verificar se um binário existe localmente, exceto ao tentar carregar a id de blob.
Se a id for carregada, os logs não exibirão esse aviso. No entanto, se não for encontrado, o standby sabe que precisa sincronizá-lo, então vemos o aviso 1 nos logs.


1: *\*AVISO\* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Ocorreu um erro ao carregar bytes do vapor durante a busca da id f68a92b3477bd194184251ec 916370f3ebd301d6e32a8980aad070d57a1845#25522
<br>java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Registro f68a92b3477bbd194184251ec916370f3ebd301d6e32a8980aad070d57a18 45 não existe
<br>    em org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3
<br>...
<br>Causado por: org.apache.jackrabbit.core.data.DataStoreException: O registro cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20 não existe
<br>    em org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)*


## Resolução


Isso está funcionando como projetado e não indica um problema com o File DataStore.

<b>Para confirmar:</b>

- Exemplo de id de blob mostrando como ausente nos logs: &quot;cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c2 0&quot;
- Para essa id de blob, o endereço do sistema de arquivos deve ser: &quot;ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c 49c20&quot;
- Pesquise o sistema de arquivos na instância autônoma e verifique se o arquivo nomeado está presente no armazenamento de dados.
- Dentro de /repository/datastore, use o comando list (ls -ald): &quot;ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f193 5a2c49c20&quot;
- Você deve conseguir ver o arquivo e confirmar que a ID do blob realmente não está ausente
